apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskdb-app
  template:
    metadata:
      labels:
        app: taskdb-app
    spec:
      containers:
        - name: taskdb-app
          image: confidencedev/taskdb
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: GOOGLE_CLIENT_ID
              value: ""
            - name: GOOGLE_CLIENT_SECRET
              value: ""
            - name: GITHUB_CLIENT_ID
              value: "{{GITHUB-CLIENT-ID}}"
            - name: GITHUB_CLIENT_SECRET
              value: "{{GITHUB-CLIENT-SECRET}}"
            - name: SESSION_SECRET
              value: "{{SESSION-SECRET}}"
            - name: DB_NAME
              value: "{{DB-NAME}}"
            - name: DB_USERNAME
              value: "{{DB-USERNAME}}"
            - name: DB_PASSWORD
              value: "{{DB-PASSWORD}}"
            - name: DB_HOST
              value: "{{DB-HOST}}"
            - name: DB_DIALECT
              value: "{{DB-DIALECT}}"
---
apiVersion: v1
kind: Service
metadata:
  name: taskdb-svc
spec:
  type: LoadBalancer
  selector:
    app: creator-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
