name: CI-CD

env:
 resourceGroup: "learn"
 clusterName: "taskcluster"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: confidencedev/taskdb
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: '5b949fd9-aca7-47d2-ad52-72764eca04ab'
          tenant-id: 'aea4de64-772e-46f6-84c3-a12ef6e8899c'
          subscription-id: '86faab24-a754-426c-9e08-f54a249d5dba'
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list
