name: CI-CD

env:
  resourceGroup: "learn"
  clusterName: "taskcluster"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build and Push Docker Image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: confidencedev/taskdb
      #     tags: latest
      #     registry: docker.io
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.resourceGroup }} --name ${{ env.clusterName }}

      - name: Install kubectl cli
        run: |
          sudo az aks install-cli

      - name: Get Azure Key Vault secrets
        id: get_secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          # command: get
          secrets: |
            DB-DIALECT
            DB-HOST
            DM-NAME
            DB-PASSWORD
            DB-USERNAME
            GITHUB-CLIENT-ID
            GITHUB-CLIENT-SECRET
            GOOGLE-CLIENT-ID
            GOOGLE-CLIENT-SECRET
            SESSION-SECRET

          keyvault: ${{ secrets.VAULT }}
          # azSubscription: ${{ secrets.SUBSCRIPTION }}
          # azResourceGroup: ${{ secrets.GROUP }}

      - name: Use Key Vault secrets
        run: |
          echo "Secret 1: ${{ steps.get_secrets.outputs.DB-DIALECT }}"
          echo "Secret 1: ${{ steps.get_secrets.outputs.DB-HOST }}"

      # - name: Apply Secrets Deploy to Kubernetes
      #   run: |
      #     sed -e "s/{{${{ steps.get_secrets.outputs.DB-DIALECT }}}}/${DB-DIALECT}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.DB-HOST }}}}/${DB-HOST}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.DB-NAME }}}}/${DB-NAME}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.DB-PASSWORD }}}}/${DB-PASSWORD}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.DB-USERNAME }}}}/${DB-USERNAME}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.GITHUB-CLIENT-ID }}}}/${GITHUB-CLIENT-ID}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.GITHUB-CLIENT-SECRET }}}}/${GITHUB-CLIENT-SECRET}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.GOOGLE-CLIENT-ID }}}}/${GOOGLE-CLIENT-ID}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.GOOGLE-CLIENT-SECRET }}}}/${GOOGLE-CLIENT-SECRET}/g" \
      #         -e "s/{{${{ steps.get_secrets.outputs.SESSION-SECRET }}}}/${SESSION-SECRET}/g" \
      #         k8s/deployment.yaml | kubectl apply -f -
