name: CI-CD

env:
 resourceGroup: "learn"
 clusterName: "taskcluster"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
 id-token: write
 contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ resourceGroup }} --name ${{ clusterName }}

      - name: Install kubectl
        run: |
          sudo az aks install-cli

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yml

