name: CI-CD

env:
  resourceGroup: "learn"
  clusterName: "taskcluster"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: confidencedev/taskdb
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.resourceGroup }} --name ${{ env.clusterName }}

      - name: Install kubectl cli
        run: |
          sudo az aks install-cli

      - name: Install secrets-store.csi.x-k8s.io CRDs
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v1.3.0/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v1.3.0/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yml
