name: CI-CD

env:
 resourceGroup: "learn"
 clusterName: "taskcluster"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: confidencedev/taskdb
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.resourceGroup }} --name ${{ env.clusterName }}

      - name: Install kubectl
        run: |
          sudo az aks install-cli

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yml 
